/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ud1_practica3;

import clases.Reparacion;
import clases.Vehiculo;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Clase encargada de añadir nuevas reparaciones a la tabla y lista de 
 * reparaciones
 * 
 * @author Daniel
 */
public class NewRepJDialog extends javax.swing.JDialog {
    ReparacionesJDialog reparacionesJDialog;
    
    int codRep, horas, codMeca, CantPiezas;
    boolean terminada;
    String matricula, telf;
    Double precioReparacion;
    Date entrada, salida;
    ArrayList<String> piezas = new ArrayList<>();
    
    /**
     * Creates new form NewRepJDialog
     */
    public NewRepJDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        reparacionesJDialog = (ReparacionesJDialog) parent;
        initComponents();
        
        jTextFieldCodRep.setText(Integer.toString(
                reparacionesJDialog.principal.datos.getReparaciones().size() + 1));
        jTextFieldCodMecanico.setText(Integer.toString(
                reparacionesJDialog.principal.mechanic.getCodigo()));
        
        
        for (int i = 0; i < reparacionesJDialog.principal.datos.getVehiculos().size(); i++) {
            jComboBoxMatricula.addItem(reparacionesJDialog.principal.datos
                    .getVehiculos().get(i).getMatricula());
        }
        
        for (int i = 0; i < reparacionesJDialog.principal.datos.getClientes().size(); i++) {
            jComboBoxTelfs.addItem(reparacionesJDialog.principal.datos
                    .getClientes().get(i).getTelefono().toString());
        }
        
        jTextAreaPiezas.setEditable(false);
        jTextAreaPiezas.setText(piezas.toString());
        
        jButtonAceptar.setMnemonic('a');
        jButtonCancelar.setMnemonic('b');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNuevRepTit = new javax.swing.JLabel();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelHoras = new javax.swing.JLabel();
        jRadioButtonTerminada = new javax.swing.JRadioButton();
        jTextFieldHoras = new javax.swing.JTextField();
        jComboBoxPiezas = new javax.swing.JComboBox<>();
        jLabelPiezas = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldCodRep = new javax.swing.JTextField();
        jLabelCodMeca = new javax.swing.JLabel();
        jTextFieldCodMecanico = new javax.swing.JTextField();
        jLabelMatricula = new javax.swing.JLabel();
        jComboBoxMatricula = new javax.swing.JComboBox<>();
        jComboBoxTelfs = new javax.swing.JComboBox<>();
        jLabelTelfContacto = new javax.swing.JLabel();
        jButtonAnyaPiez = new javax.swing.JButton();
        jButtonEliminarPiez = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPiezas = new javax.swing.JTextArea();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNuevRepTit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelNuevRepTit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNuevRepTit.setText("Nueva reparación");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("ALT+A");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("ALT+B");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelHoras.setText("Horas Invertidas");

        jRadioButtonTerminada.setText("Terminada");

        jTextFieldHoras.setToolTipText("");

        jComboBoxPiezas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Junta de la trocola", "Rueda", "Palo de marchas", "Aceite", "Suspensiones", "Radio" }));

        jLabelPiezas.setText("Piezas");

        jLabelId.setText("Nº Reparación");

        jTextFieldCodRep.setEditable(false);

        jLabelCodMeca.setText("Cod. Mecanico");

        jTextFieldCodMecanico.setEditable(false);

        jLabelMatricula.setText("Matrícula");

        jLabelTelfContacto.setText("Telf.Contacto");

        jButtonAnyaPiez.setText("Añadir");
        jButtonAnyaPiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyaPiezActionPerformed(evt);
            }
        });

        jButtonEliminarPiez.setText("Eliminar 1");
        jButtonEliminarPiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPiezActionPerformed(evt);
            }
        });

        jTextAreaPiezas.setColumns(20);
        jTextAreaPiezas.setLineWrap(true);
        jTextAreaPiezas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPiezas);

        jLabelPrecio.setText("Precio");

        jTextFieldPrecio.setText("0.00");
        jTextFieldPrecio.setToolTipText("0.00");
        jTextFieldPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPrecioFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNuevRepTit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTelfContacto)
                            .addComponent(jLabelMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCodMeca)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonTerminada)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHoras)
                                    .addComponent(jLabelPiezas)
                                    .addComponent(jLabelPrecio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonAnyaPiez)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonEliminarPiez))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldHoras, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(jComboBoxMatricula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxTelfs, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodRep, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelNuevRepTit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodMeca))
                        .addComponent(jLabelMatricula))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTelfs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelfContacto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHoras)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonTerminada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPiezas)
                            .addComponent(jComboBoxPiezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAnyaPiez)
                            .addComponent(jButtonEliminarPiez))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrecio)
                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Cierra este dialog
     * 
     * @param evt 
     */
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * Recoge todos los datos del Dialog, en caso de que sean válidos crea y 
     * añade una nueva reparación a la lista reparaciones y actualiza la tabla
     * para mostrar los cambios, al final actualiza la lista en principal.datos
     * con la lista local antes de cerrar la ventana.
     * 
     * @param evt 
     */
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        codRep = Integer.valueOf(jTextFieldCodRep.getText());
        horas = Integer.valueOf(jTextFieldHoras.getText());
        codMeca = Integer.valueOf(jTextFieldCodMecanico.getText());
        CantPiezas = piezas.size();
        terminada = jRadioButtonTerminada.isSelected();
        precioReparacion = Double.valueOf(jTextFieldPrecio.getText());
        matricula = jComboBoxMatricula.getSelectedItem().toString();
        telf = jComboBoxTelfs.getSelectedItem().toString();
        entrada = new Date();
        
        if (horas <= 0 || precioReparacion <= 0 || entrada.toString().isEmpty()
                || matricula.isEmpty() || telf.isEmpty()) {
            JOptionPane.showMessageDialog(null, 
                    "Uno o más campos están vacíos/no son válidos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else 
        {
            reparacionesJDialog.reparaciones.add(new Reparacion(codRep, horas, 
                    codMeca, CantPiezas, matricula, telf, 
                    piezas.toString(),terminada,precioReparacion));
            
            reparacionesJDialog.anyadirRep();
            
            
            reparacionesJDialog.principal.datos.setReparaciones(reparacionesJDialog.reparaciones);
            
             this.dispose();
        }
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * Añade una pieza a la lista y al textarea encargado de mostrar la 
     * seleccionadas.
     * 
     * @param evt 
     */
    private void jButtonAnyaPiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyaPiezActionPerformed
        piezas.add(jComboBoxPiezas.getSelectedItem().toString());
        jTextAreaPiezas.setText(piezas.toString());
    }//GEN-LAST:event_jButtonAnyaPiezActionPerformed

    /**
     * Elimina una pieza a la lista y al textarea encargado de mostrar la 
     * seleccionadas.
     * 
     * @param evt 
     */
    
    private void jButtonEliminarPiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPiezActionPerformed
        piezas.remove(jComboBoxPiezas.getSelectedItem().toString());
        jTextAreaPiezas.setText(piezas.toString());
    }//GEN-LAST:event_jButtonEliminarPiezActionPerformed

    /**
     * Cuando se selecciona el texfield de precio el ejemplo desaparece.
     * @param evt 
     */
    private void jTextFieldPrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecioFocusGained
        jTextFieldPrecio.setText("");
    }//GEN-LAST:event_jTextFieldPrecioFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewRepJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewRepJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewRepJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewRepJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewRepJDialog dialog = new NewRepJDialog(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAnyaPiez;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminarPiez;
    private javax.swing.JComboBox<String> jComboBoxMatricula;
    private javax.swing.JComboBox<String> jComboBoxPiezas;
    private javax.swing.JComboBox<String> jComboBoxTelfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCodMeca;
    private javax.swing.JLabel jLabelHoras;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNuevRepTit;
    private javax.swing.JLabel jLabelPiezas;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTelfContacto;
    private javax.swing.JRadioButton jRadioButtonTerminada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaPiezas;
    private javax.swing.JTextField jTextFieldCodMecanico;
    private javax.swing.JTextField jTextFieldCodRep;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldPrecio;
    // End of variables declaration//GEN-END:variables
}
