/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud1_practica3;

import clases.Datos;
import clases.Mecanico;
import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.synth.SynthLookAndFeel;

/**
 * Clase principal desde la cual se puede acceder a clientes, vehículos y 
 * reparaciones además de poseer el botón para cambiar el aspecto de la 
 * aplicación.
 *
 * @author DAM2Alu5
 */
public class Principal extends javax.swing.JFrame {
    public Mecanico mechanic;
    public Datos datos = new Datos();
    boolean temaDia = true;
    /**
     * Creates new form Entrada. Pone de icono la imagen icono.png
     */
    public Principal() {
        initComponents();
        setIconImage(new ImageIcon("imagenes/icono.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelImgStock = new javax.swing.JLabel();
        jButtonClient = new javax.swing.JButton();
        jButtonVehi = new javax.swing.JButton();
        jButtonRepar = new javax.swing.JButton();
        jButtonTheme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("TALLERES FITIPALDI");

        jLabelImgStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ud1_practica3/mecanicoStock2.jpg"))); // NOI18N
        jLabelImgStock.setMinimumSize(new java.awt.Dimension(600, 400));

        jButtonClient.setText("Clientes");
        jButtonClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientActionPerformed(evt);
            }
        });

        jButtonVehi.setText("Vehículos");
        jButtonVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiActionPerformed(evt);
            }
        });

        jButtonRepar.setText("Reparaciones");
        jButtonRepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReparActionPerformed(evt);
            }
        });

        jButtonTheme.setText("Tema");
        jButtonTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButtonClient)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVehi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRepar)
                        .addGap(18, 218, Short.MAX_VALUE)
                        .addComponent(jButtonTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelImgStock, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImgStock, javax.swing.GroupLayout.PREFERRED_SIZE, 284, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonClient)
                            .addComponent(jButtonVehi)
                            .addComponent(jButtonRepar))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonTheme)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    /**
     * En caso de que temaDia sea true aplica el lookAndFeel Motif y settea 
     * temaDia a false.
     * En caso de que temaDia sea false aplica el lookAndFeel WindowsClassic
     * y settea el tema día a true;
     * 
     * Al final de ambos casos actualiza la ventana actual;
     * 
     * @param evt 
     */
    private void jButtonThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemeActionPerformed
        if(temaDia)
        {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                temaDia=false;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }             
        }
        else
        {
            try {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
                temaDia=true;
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        SwingUtilities.updateComponentTreeUI(this);
    }//GEN-LAST:event_jButtonThemeActionPerformed

    /**
     * Accede al dialog que muestra e interactua con clientes.
     * 
     * @param evt 
     */
    private void jButtonClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientActionPerformed
        ClientesDialog dialogoClient = new ClientesDialog(this, true);
        dialogoClient.setTitle("Clientes");
        dialogoClient.setVisible(true);
    }//GEN-LAST:event_jButtonClientActionPerformed

    /**
     * Accede al dialog que muestra e interactua con vehículos
     * 
     * @param evt 
     */
    private void jButtonVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiActionPerformed
        VehiculosDialog vehiculosDialog = new VehiculosDialog(this, true);
        vehiculosDialog.setTitle("Vehículos");
        vehiculosDialog.setVisible(true);
    }//GEN-LAST:event_jButtonVehiActionPerformed

    /**
     * Accede al dialog que muestra e interactua con las reparaciones.
     * 
     * @param evt 
     */
    private void jButtonReparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReparActionPerformed
        ReparacionesJDialog reparacionesJDialog = new ReparacionesJDialog(this, true);
        reparacionesJDialog.setTitle("Reparaciones");
        reparacionesJDialog.setVisible(true);
    }//GEN-LAST:event_jButtonReparActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClient;
    private javax.swing.JButton jButtonRepar;
    private javax.swing.JButton jButtonTheme;
    private javax.swing.JButton jButtonVehi;
    private javax.swing.JLabel jLabelImgStock;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
