/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ud1_practica3;

import clases.Reparacion;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase con tabla para mostrar las reparaciones guardadas en lista desde la 
 * cual también se pueden borrar de la lista y de la tabla.
 *
 * @author Daniel
 */
public class ReparacionesJDialog extends javax.swing.JDialog {
    Principal principal;
    ArrayList<Reparacion> reparaciones;
    
    DefaultTableModel dtm;
    String[] cabeceras = {"Cod.Reparacion","Mecanico","Matrícula",
        "Telf. Contacto","Terminada","Horas","Piezas", "Cant.Piezas", 
        "Precio.Rep"};
    
    /**
     * Creates new form ReparacionesJDialog
     */
    public ReparacionesJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        principal = (Principal) parent;
        reparaciones = principal.datos.getReparaciones();
        initComponents();
        
        dtm = new DefaultTableModel(cabeceras, 0);
        jTableRep.setModel(dtm);
        
        anyadirRep();
        jButtonAnyadir.setMnemonic('a');
        jButtonEliminar.setMnemonic('e');
        jButtonCancelar.setMnemonic('b');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRepTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRep = new javax.swing.JTable();
        jButtonAnyadir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelRepTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelRepTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRepTitle.setText("Reparaciones");

        jTableRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRep);

        jButtonAnyadir.setText("Añadir");
        jButtonAnyadir.setToolTipText("ALT+A");
        jButtonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("ALT+B");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setToolTipText("ALT+E");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelRepTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnyadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelRepTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnyadir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Vacia la tabla de cualquier reparacion y pone las lineas a 0,
     * por cada reparación, en la lista mete los datos de la reparación en un 
     * array que luego reparte al añadir una row con los datos de dicha 
     * reparación que settea el dtm a la tabla de nuevo.
     */
    public void anyadirRep()
    {
        jTableRep.removeAll();
        dtm.setRowCount(0);
        String[] repDatos = new String[9];
        
        for (Reparacion r : reparaciones) {
            repDatos[0] = Integer.toString(r.getCodRep());
            repDatos[1] = Integer.toString(r.getCodMeca());
            repDatos[2] = r.getMatriculaVehi();
            repDatos[3] = r.getTelfProp();
            repDatos[4] = Boolean.toString(r.isTerminada());
            repDatos[5] = Integer.toString(r.getHoras());
            
            repDatos[6] = r.getPiezasStr().toString();
            repDatos[7] = Integer.toString(r.getCantPiezas());
            repDatos[8] = Double.toString(r.getPrecioReparacion());
            
            dtm.addRow(repDatos);
        }
        jTableRep.setModel(dtm);
    }
    
    
    /**
     * Cierra este dialog.
     * 
     * @param evt 
     */
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * Crea una nueva ventana para añadir una reparación nueva.
     * 
     * @param evt 
     */
    
    private void jButtonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirActionPerformed
        NewRepJDialog newRepJDialog = new NewRepJDialog(this, false);
        newRepJDialog.setTitle("Nueva Reparación");
        newRepJDialog.setVisible(true);
    }//GEN-LAST:event_jButtonAnyadirActionPerformed

    /**
     * Elimina la línea de la tabla seleccionada, tanot de la tabla como del 
     * array de reparaciones, en caso de no estarlo lanza un showDialog para 
     * advertir del hecho.
     */
    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        try {
        if (dtm.getRowCount() == 0) {
                throw new IllegalAccessException();
            }
            if (jTableRep.getSelectedRow() < 0) {
                throw new Exception();
            }
        String id = dtm.getValueAt(jTableRep.getSelectedRow(), 0).toString();
        ListIterator<Reparacion> it = reparaciones.listIterator();
        
        while(it.hasNext())
        {
            Reparacion r = it.next();
            if(r.getCodRep() == Integer.valueOf(id))
            {
                it.remove();
            }
        }
        dtm.removeRow(jTableRep.getSelectedRow());
        principal.datos.setReparaciones(reparaciones);
        
        } catch (IllegalAccessException ex) {
                JOptionPane.showMessageDialog(null, 
                        "Tabla vacía", "ERROR", 
                        JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                    "Reparación sin seleccionar", "ERROR", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReparacionesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReparacionesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReparacionesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReparacionesJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReparacionesJDialog dialog = new ReparacionesJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnyadir;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabelRepTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRep;
    // End of variables declaration//GEN-END:variables
}
