/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ud1_practica3;

import clases.Cliente;
import clases.Vehiculo;
import java.util.ArrayList;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Clase con tabla para mostrar los vehículos guardados en lista desde la 
 * cual también se pueden borrar de la lista y de la tabla.
 *
 * @author DAM2Alu5
 */
public class VehiculosDialog extends javax.swing.JDialog {
    Principal principal;
    ArrayList<Vehiculo> vehiculos;
    
    DefaultTableModel dtm;
    String[] cabeceras = {"Matrícula", "Modelo", "Marca", "Propietario"};
    
    public String regexMatri, regexTelf;
    
    /**
     * Creates new form VehiculosDialog. Se asigna el jFrame Principal como padre
     * el ArrayList Vehiculos se llena con una copia del Arraylist vehiculos en 
     * principal.datos, se inicializan los componentes, se crea un nuevo 
     * DefaultTableModel que se aplica a la tabal. Se actualiza la tabla en caso
     * de que ya hayan vehículos. Se asigna los regex necesarios.
     */
    public VehiculosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        principal = (Principal) parent;
        vehiculos = principal.datos.getVehiculos();
        initComponents();
        
        dtm = new DefaultTableModel(cabeceras, 0);
        jTableVehi.setModel(dtm);
        anyadirVehi();
        
        jButtonAnya.setMnemonic('a');
        jButtonDel.setMnemonic('e');
        jButtonCancelar.setMnemonic('b');
                
        regexMatri = "^[0-9]{1,4}(?!.*(LL|CH))[BCDFGHJKLMNPRSTVWXYZ]{3}";
        regexTelf = "(\\+34|0034|34)?(6|7|8|9)([0-9]){8}";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVehi = new javax.swing.JTable();
        jLabelTitleVehi = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAnya = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableVehi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matrícula", "Modelo", "Marca", "Propietario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVehi);

        jLabelTitleVehi.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelTitleVehi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleVehi.setText("Vehículos");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setToolTipText("ALT+B");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAnya.setText("Añadir");
        jButtonAnya.setToolTipText("ALT+A");
        jButtonAnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyaActionPerformed(evt);
            }
        });

        jButtonDel.setText("Eliminar");
        jButtonDel.setToolTipText("ALT+E");
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabelTitleVehi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(jButtonCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitleVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAnya)
                    .addComponent(jButtonDel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Vacia la tabla de cualquier vehículo y pone las líneas a 0,
     * por cada vehículo en la lista mete los datos del vehiculo en un array 
     * que luego se reparte al añadir una row con los datos de dicho vehículo
     * settea el dtm a la tabla de nuevo.
     */
    public void anyadirVehi()
    {
        jTableVehi.removeAll();
        dtm.setRowCount(0);
        String[] vehiDatos = new String[4];
        for (Vehiculo vehiculo : vehiculos) {
            vehiDatos[0] = vehiculo.getMatricula();
            vehiDatos[1] = vehiculo.getModelo();
            vehiDatos[2] = vehiculo.getMarca();
            vehiDatos[3] = vehiculo.getTelfPropietario();
            
            dtm.addRow(vehiDatos);
        }
        jTableVehi.setModel(dtm);
    }
    
    
    /**
     * Cierra este dialog.
     * 
     * @param evt 
     */
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * Llama al dialog encargado de añadir vehículos.
     * 
     * @param evt 
     */
    private void jButtonAnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyaActionPerformed
        NewVehiJDialog newVehiJDialog = new NewVehiJDialog(this, false);
        newVehiJDialog.setTitle("Añadir vehículo");
        newVehiJDialog.setVisible(true);
    }//GEN-LAST:event_jButtonAnyaActionPerformed

    /**
     * Si no hay vehiculos en la tabla o ninguno está seleccionado lanza errores
     * que invocan un OptionPane para el usuario.
     * 
     * Selecciona la matrícula del vehículo en la row seleccionada y crea un 
     * ListIterator. Mientras queden elementos en el ListIterator crea un 
     * Vehículo temportal con los datos del vehiculo en el momento actual del 
     * bucle. Si su matrícula es igual a la seleccionada lo elimina de la lista
     * el dtm elimina su row de la tabla y se actualiza el ArrayList de vehículos
     * de principal.datos
     * @param evt 
     */
    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        try {
        if (dtm.getRowCount() == 0) {
                throw new IllegalAccessException();
            }
            if (jTableVehi.getSelectedRow() < 0) {
                throw new Exception();
            }
        String matricula = dtm.getValueAt(jTableVehi.getSelectedRow(), 0).toString();
        ListIterator<Vehiculo> it = vehiculos.listIterator();
        
        while(it.hasNext())
        {
            Vehiculo vehiculo = it.next();
            if(vehiculo.getMatricula().equals(matricula))
            {
                it.remove();
            }
        }
        dtm.removeRow(jTableVehi.getSelectedRow());
        principal.datos.setVehiculos(vehiculos);
        
        } catch (IllegalAccessException ex) {
                JOptionPane.showMessageDialog(null, 
                        "Tabla vacía", "ERROR", 
                        JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                    "Vehículo sin seleccionar", "ERROR", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VehiculosDialog dialog = new VehiculosDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnya;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JLabel jLabelTitleVehi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVehi;
    // End of variables declaration//GEN-END:variables
}
