
import java.util.Enumeration;
import javax.swing.JRadioButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DAM2Alu5
 */
public class JFrameColores extends javax.swing.JFrame {

    /**
     * Creates new form JFrameColores
     */
    public JFrameColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupColores = new javax.swing.ButtonGroup();
        jPanelColores = new javax.swing.JPanel();
        jRadioRojo = new javax.swing.JRadioButton();
        jRadioVerde = new javax.swing.JRadioButton();
        jRadioAzul = new javax.swing.JRadioButton();
        jButtonAcceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelColores.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(JFrameColores.class, "JFrameColores.jPanelColores.border.title"))); // NOI18N

        buttonGroupColores.add(jRadioRojo);
        jRadioRojo.setText(org.openide.util.NbBundle.getMessage(JFrameColores.class, "JFrameColores.jRadioRojo.text")); // NOI18N

        buttonGroupColores.add(jRadioVerde);
        jRadioVerde.setText(org.openide.util.NbBundle.getMessage(JFrameColores.class, "JFrameColores.jRadioVerde.text")); // NOI18N
        jRadioVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioVerdeActionPerformed(evt);
            }
        });

        buttonGroupColores.add(jRadioAzul);
        jRadioAzul.setText(org.openide.util.NbBundle.getMessage(JFrameColores.class, "JFrameColores.jRadioAzul.text")); // NOI18N

        javax.swing.GroupLayout jPanelColoresLayout = new javax.swing.GroupLayout(jPanelColores);
        jPanelColores.setLayout(jPanelColoresLayout);
        jPanelColoresLayout.setHorizontalGroup(
            jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioRojo)
                    .addComponent(jRadioVerde)
                    .addComponent(jRadioAzul))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelColoresLayout.setVerticalGroup(
            jPanelColoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioRojo)
                .addGap(18, 18, 18)
                .addComponent(jRadioVerde)
                .addGap(18, 18, 18)
                .addComponent(jRadioAzul)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jButtonAcceptar.setText(org.openide.util.NbBundle.getMessage(JFrameColores.class, "JFrameColores.jButtonAcceptar.text")); // NOI18N
        jButtonAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcceptarActionPerformed(evt);
            }
        });

        jLabelColor.setText(org.openide.util.NbBundle.getMessage(JFrameColores.class, "JFrameColores.jLabelColor.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelColor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelColor)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAcceptar))
                        .addGap(0, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelColores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAcceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioVerdeActionPerformed
        
    }//GEN-LAST:event_jRadioVerdeActionPerformed

    private void jButtonAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcceptarActionPerformed
     Enumeration e = buttonGroupColores.getElements();
     
     while (e.hasMoreElements()){
         JRadioButton r = (JRadioButton) e.nextElement();
         if (r.isSelected()){
             jLabelColor.setText("Color elegido: " + r.getText());
         }
     }
        /*   if (jRadioVerde.isSelected()) {
            jLabelColor.setText("Color elegido: Verde");
        } else if (jRadioRojo.isSelected()) {
            jLabelColor.setText("Color elegido: Rojo");
        } else {
            jLabelColor.setText("Color elegido: Azul");
        }*/
        
    }//GEN-LAST:event_jButtonAcceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameColores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupColores;
    private javax.swing.JButton jButtonAcceptar;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelColores;
    private javax.swing.JRadioButton jRadioAzul;
    private javax.swing.JRadioButton jRadioRojo;
    private javax.swing.JRadioButton jRadioVerde;
    // End of variables declaration//GEN-END:variables
}
