/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud1_practica1.pkg2;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author DAM2Alu5
 */
public class garaje extends javax.swing.JFrame {
    boolean camion;
    DefaultComboBoxModel dcbm;
    ArrayList<Vehiculo> vehiculos;
    /**
     * Creates new form garaje
     */
    public garaje() {
        initComponents();
        vehiculos = new ArrayList<>();
        String opciones[] = {"Coche", "Furgoneta", "Camión"};
        for (String s : opciones) {
            jComboBoxVehi.addItem(s);
        }
        dcbm = new DefaultComboBoxModel();
        jComboBoxVehAlta.removeAllItems();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPropNom = new javax.swing.JLabel();
        jLabelPropApe = new javax.swing.JLabel();
        jTextFieldPropNom = new javax.swing.JTextField();
        jTextFieldPropApe = new javax.swing.JTextField();
        jLabelPropTelf = new javax.swing.JLabel();
        jTextFieldPropTelf = new javax.swing.JTextField();
        jLabelPropDNI = new javax.swing.JLabel();
        jTextFieldPropDNI = new javax.swing.JTextField();
        jPanelVeh = new javax.swing.JPanel();
        jLabelVehTip = new javax.swing.JLabel();
        jComboBoxVehi = new javax.swing.JComboBox<>();
        jLabelVehFech = new javax.swing.JLabel();
        jSpinnerVehFech = new javax.swing.JSpinner();
        jLabelVehMod = new javax.swing.JLabel();
        jTextFieldVehMod = new javax.swing.JTextField();
        jLabelVehMatr = new javax.swing.JLabel();
        jTextFieldVehMatr = new javax.swing.JTextField();
        jLabelCamLong = new javax.swing.JLabel();
        jTextFieldCamLong = new javax.swing.JTextField();
        jLabelCamMer = new javax.swing.JLabel();
        jCheckBoxCamMer = new javax.swing.JCheckBox();
        jButtonAnyadir = new javax.swing.JButton();
        jComboBoxVehAlta = new javax.swing.JComboBox<>();
        jLabelVehAlta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Propietario"));

        jLabelPropNom.setText("Nombre:");

        jLabelPropApe.setText("Apellidos");

        jLabelPropTelf.setText("Telf:");

        jLabelPropDNI.setText("DNI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPropNom)
                    .addComponent(jLabelPropTelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPropTelf, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jTextFieldPropNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPropApe)
                    .addComponent(jLabelPropDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPropApe)
                    .addComponent(jTextFieldPropDNI))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPropNom)
                    .addComponent(jTextFieldPropNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPropApe)
                        .addComponent(jTextFieldPropApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPropTelf)
                        .addComponent(jTextFieldPropTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPropDNI))
                    .addComponent(jTextFieldPropDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelVeh.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehículo"));

        jLabelVehTip.setText("Tipo:");

        jComboBoxVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVehiActionPerformed(evt);
            }
        });

        jLabelVehFech.setText("Fecha de entrada:");

        jSpinnerVehFech.setModel(new javax.swing.SpinnerDateModel());

        jLabelVehMod.setText("Modelo:");

        jLabelVehMatr.setText("Matrícula:");

        jLabelCamLong.setText("Longitud:");

        jLabelCamMer.setText("Mercancía Peligrosa:");

        javax.swing.GroupLayout jPanelVehLayout = new javax.swing.GroupLayout(jPanelVeh);
        jPanelVeh.setLayout(jPanelVehLayout);
        jPanelVehLayout.setHorizontalGroup(
            jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addComponent(jLabelVehTip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehMod)
                            .addComponent(jLabelCamLong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVehMod)
                            .addComponent(jTextFieldCamLong, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehFech)
                            .addComponent(jLabelVehMatr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerVehFech, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTextFieldVehMatr)))
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addComponent(jLabelCamMer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCamMer)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVehLayout.setVerticalGroup(
            jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehTip)
                    .addComponent(jComboBoxVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehFech)
                    .addComponent(jSpinnerVehFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehMod)
                    .addComponent(jTextFieldVehMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehMatr)
                    .addComponent(jTextFieldVehMatr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamLong)
                    .addComponent(jTextFieldCamLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCamMer)
                    .addComponent(jCheckBoxCamMer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAnyadir.setText("Añadir");
        jButtonAnyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnyadirActionPerformed(evt);
            }
        });

        jComboBoxVehAlta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelVehAlta.setText("Vehículos de alta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelVeh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAnyadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelVehAlta)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxVehAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnyadir)
                    .addComponent(jComboBoxVehAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehAlta))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnyadirActionPerformed
        try {
            String form = "dd/MM/yyyy";
            SimpleDateFormat sdf = new SimpleDateFormat(form);
            
            if(jTextFieldPropNom.getText().isEmpty() ||
                jTextFieldPropApe.getText().isEmpty() ||
                jTextFieldPropTelf.getText().isEmpty() ||
                jTextFieldPropDNI.getText().isEmpty() ||
                jTextFieldVehMatr.getText().isEmpty() ||
                jTextFieldVehMod.getText().isEmpty()
                )
            {
            throw new Exception();
            } //End if vacio
            
            if (camion)
            {
                boolean peligro = false;
                if(jCheckBoxCamMer.isSelected()){
                    peligro = true;
                }
                if(jTextFieldCamLong.getText().isEmpty())
                {
                    throw new Exception();
                }//END if camión vacio
                else 
                {
                    Camion c = new Camion(
                            Double.parseDouble(jTextFieldCamLong.getText()),
                            peligro,
                            jTextFieldVehMod.getText(),
                            jTextFieldVehMatr.getText(),
                            jComboBoxVehi.getSelectedItem().toString(),
                            jTextFieldPropNom.getText(),
                            jTextFieldPropApe.getText(),
                            jTextFieldPropDNI.getText(),
                            (Date) jSpinnerVehFech.getValue()
                    );//fin nuevo camion
                    vehiculos.add(c);
                }
            }//End if camión
            else
            {
                Vehiculo v = new Vehiculo(
                            jTextFieldVehMod.getText(),
                            jTextFieldVehMatr.getText(),
                            jComboBoxVehi.getSelectedItem().toString(),
                            jTextFieldPropNom.getText(),
                            jTextFieldPropApe.getText(),
                            jTextFieldPropDNI.getText(),
                            (Date) jSpinnerVehFech.getValue()
                );//Fin nuevo vehi
                vehiculos.add(v);
            }
            dcbm.removeAllElements();
            
            for (Vehiculo vehiculo : vehiculos) {
                dcbm.addElement("Modelo " + vehiculo.getModelo() + ", Matrícula "
                        + vehiculo.getMatricula() + ", fecha " + 
                        sdf.format(vehiculo.getFecha()));
            } //End foreach
            
            jComboBoxVehAlta.setModel(dcbm);
            jTextFieldVehMatr.setText("");
            jTextFieldVehMod.setText("");
            jTextFieldCamLong.setText("");
            jTextFieldPropApe.setText("");
            jTextFieldPropDNI.setText("");
            jTextFieldPropNom.setText("");
            jTextFieldPropTelf.setText("");
            jCheckBoxCamMer.setSelected(false);
            
        } 
        catch (Exception ex) 
        {
            Logger.getLogger(garaje.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_jButtonAnyadirActionPerformed

    private void jComboBoxVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVehiActionPerformed
        if(jComboBoxVehi.getSelectedIndex()!=2){
            jTextFieldCamLong.setEnabled(false);
            jCheckBoxCamMer.setEnabled(false);
            camion = false;
        } else {
            jTextFieldCamLong.setEnabled(true);
            jCheckBoxCamMer.setEnabled(true);
            camion = true;
        }
    }//GEN-LAST:event_jComboBoxVehiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(garaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(garaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(garaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(garaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new garaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnyadir;
    private javax.swing.JCheckBox jCheckBoxCamMer;
    private javax.swing.JComboBox<String> jComboBoxVehAlta;
    private javax.swing.JComboBox<String> jComboBoxVehi;
    private javax.swing.JLabel jLabelCamLong;
    private javax.swing.JLabel jLabelCamMer;
    private javax.swing.JLabel jLabelPropApe;
    private javax.swing.JLabel jLabelPropDNI;
    private javax.swing.JLabel jLabelPropNom;
    private javax.swing.JLabel jLabelPropTelf;
    private javax.swing.JLabel jLabelVehAlta;
    private javax.swing.JLabel jLabelVehFech;
    private javax.swing.JLabel jLabelVehMatr;
    private javax.swing.JLabel jLabelVehMod;
    private javax.swing.JLabel jLabelVehTip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelVeh;
    private javax.swing.JSpinner jSpinnerVehFech;
    private javax.swing.JTextField jTextFieldCamLong;
    private javax.swing.JTextField jTextFieldPropApe;
    private javax.swing.JTextField jTextFieldPropDNI;
    private javax.swing.JTextField jTextFieldPropNom;
    private javax.swing.JTextField jTextFieldPropTelf;
    private javax.swing.JTextField jTextFieldVehMatr;
    private javax.swing.JTextField jTextFieldVehMod;
    // End of variables declaration//GEN-END:variables
}
