/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ud1_practica1.pkg2;

import javax.swing.JLabel;

/**
 *
 * @author DAM2Alu5
 */
public class JDialogAnyadir extends javax.swing.JDialog {
   
    
    /**
     * Creates new form JDialogAnyadir
     */
    public JDialogAnyadir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVeh = new javax.swing.JPanel();
        jLabelVehTip = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabelVehFech = new javax.swing.JLabel();
        jSpinnerVehFech = new javax.swing.JSpinner();
        jLabelVehMod = new javax.swing.JLabel();
        jTextFieldVehMod = new javax.swing.JTextField();
        jLabelVehMatr = new javax.swing.JLabel();
        jTextFieldVehMatr = new javax.swing.JTextField();
        jLabelCamLong = new javax.swing.JLabel();
        jTextFieldCamLong = new javax.swing.JTextField();
        jLabelCamMer = new javax.swing.JLabel();
        jCheckBoxCamMer = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelPropNom = new javax.swing.JLabel();
        jLabelPropApe = new javax.swing.JLabel();
        jTextFieldPropNom = new javax.swing.JTextField();
        jTextFieldPropApe = new javax.swing.JTextField();
        jLabelPropTelf = new javax.swing.JLabel();
        jTextFieldPropTelf = new javax.swing.JTextField();
        jLabelPropDNI = new javax.swing.JLabel();
        jTextFieldPropDNI = new javax.swing.JTextField();
        jPanelVeh1 = new javax.swing.JPanel();
        jLabelVehTip1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabelVehFech1 = new javax.swing.JLabel();
        jSpinnerVehFech1 = new javax.swing.JSpinner();
        jLabelVehMod1 = new javax.swing.JLabel();
        jTextFieldVehMod1 = new javax.swing.JTextField();
        jLabelVehMatr1 = new javax.swing.JLabel();
        jTextFieldVehMatr1 = new javax.swing.JTextField();
        jLabelCamLong1 = new javax.swing.JLabel();
        jTextFieldCamLong1 = new javax.swing.JTextField();
        jLabelCamMer1 = new javax.swing.JLabel();
        jCheckBoxCamMer1 = new javax.swing.JCheckBox();
        jButtonAlta = new javax.swing.JButton();
        jLabelMsg = new javax.swing.JLabel();

        jPanelVeh.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehículo"));

        jLabelVehTip.setText("Tipo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coche", "Furgoneta", "Camión" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabelVehFech.setText("Fecha de entrada:");

        jSpinnerVehFech.setModel(new javax.swing.SpinnerDateModel());

        jLabelVehMod.setText("Modelo:");

        jTextFieldVehMod.setEditable(false);

        jLabelVehMatr.setText("Matrícula:");

        jTextFieldVehMatr.setEditable(false);

        jLabelCamLong.setText("Longitud:");

        jTextFieldCamLong.setEditable(false);

        jLabelCamMer.setText("Mercancía Peligrosa:");

        javax.swing.GroupLayout jPanelVehLayout = new javax.swing.GroupLayout(jPanelVeh);
        jPanelVeh.setLayout(jPanelVehLayout);
        jPanelVehLayout.setHorizontalGroup(
            jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addComponent(jLabelVehTip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehMod)
                            .addComponent(jLabelCamLong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVehMod)
                            .addComponent(jTextFieldCamLong, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehFech)
                            .addComponent(jLabelVehMatr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerVehFech, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTextFieldVehMatr)))
                    .addGroup(jPanelVehLayout.createSequentialGroup()
                        .addComponent(jLabelCamMer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCamMer)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVehLayout.setVerticalGroup(
            jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVehLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehTip)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehFech)
                    .addComponent(jSpinnerVehFech, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehMod)
                    .addComponent(jTextFieldVehMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehMatr)
                    .addComponent(jTextFieldVehMatr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVehLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamLong)
                    .addComponent(jTextFieldCamLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCamMer)
                    .addComponent(jCheckBoxCamMer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Propietario"));

        jLabelPropNom.setText("Nombre:");

        jLabelPropApe.setText("Apellidos");

        jLabelPropTelf.setText("Telf:");

        jLabelPropDNI.setText("DNI:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPropNom)
                    .addComponent(jLabelPropTelf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPropTelf, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(jTextFieldPropNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPropApe)
                    .addComponent(jLabelPropDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPropApe, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jTextFieldPropDNI))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPropNom)
                    .addComponent(jTextFieldPropNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelPropApe)
                        .addComponent(jTextFieldPropApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPropTelf)
                        .addComponent(jTextFieldPropTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPropDNI))
                    .addComponent(jTextFieldPropDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelVeh1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehículo"));

        jLabelVehTip1.setText("Tipo:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coche", "Furgoneta", "Camión" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabelVehFech1.setText("Fecha de entrada:");

        jSpinnerVehFech1.setModel(new javax.swing.SpinnerDateModel());

        jLabelVehMod1.setText("Modelo:");

        jTextFieldVehMod1.setEditable(false);

        jLabelVehMatr1.setText("Matrícula:");

        jTextFieldVehMatr1.setEditable(false);

        jLabelCamLong1.setText("Longitud:");

        jTextFieldCamLong1.setEditable(false);

        jLabelCamMer1.setText("Mercancía Peligrosa:");

        javax.swing.GroupLayout jPanelVeh1Layout = new javax.swing.GroupLayout(jPanelVeh1);
        jPanelVeh1.setLayout(jPanelVeh1Layout);
        jPanelVeh1Layout.setHorizontalGroup(
            jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeh1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelVeh1Layout.createSequentialGroup()
                        .addComponent(jLabelVehTip1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVeh1Layout.createSequentialGroup()
                        .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehMod1)
                            .addComponent(jLabelCamLong1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVehMod1)
                            .addComponent(jTextFieldCamLong1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVeh1Layout.createSequentialGroup()
                        .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVehFech1)
                            .addComponent(jLabelVehMatr1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerVehFech1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jTextFieldVehMatr1)))
                    .addGroup(jPanelVeh1Layout.createSequentialGroup()
                        .addComponent(jLabelCamMer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCamMer1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVeh1Layout.setVerticalGroup(
            jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVeh1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehTip1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehFech1)
                    .addComponent(jSpinnerVehFech1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVehMod1)
                    .addComponent(jTextFieldVehMod1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVehMatr1)
                    .addComponent(jTextFieldVehMatr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVeh1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCamLong1)
                    .addComponent(jTextFieldCamLong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCamMer1)
                    .addComponent(jCheckBoxCamMer1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAlta.setText("Dar de alta");
        jButtonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAltaActionPerformed(evt);
            }
        });

        jLabelMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMsg.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonAlta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelVeh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVeh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAltaActionPerformed
        if(jTextFieldPropNom.getText() == null || jTextFieldPropNom.getText() == "" ||
                jTextFieldPropApe.getText() == null || jLabelPropApe.getText() == "" ||
                jTextFieldPropTelf.getText() == null || jTextFieldPropTelf.getText() == "" ||
                jTextFieldPropDNI.getText() == null || jTextFieldPropDNI.getText() == "")
        {
            jLabelMsg.setText("Uno o más campos están sin completar.");
        }
        else {
            
        }
    }//GEN-LAST:event_jButtonAltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAnyadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAnyadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAnyadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAnyadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAnyadir dialog = new JDialogAnyadir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlta;
    private javax.swing.JCheckBox jCheckBoxCamMer;
    private javax.swing.JCheckBox jCheckBoxCamMer1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabelCamLong;
    private javax.swing.JLabel jLabelCamLong1;
    private javax.swing.JLabel jLabelCamMer;
    private javax.swing.JLabel jLabelCamMer1;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelPropApe;
    private javax.swing.JLabel jLabelPropDNI;
    private javax.swing.JLabel jLabelPropNom;
    private javax.swing.JLabel jLabelPropTelf;
    private javax.swing.JLabel jLabelVehFech;
    private javax.swing.JLabel jLabelVehFech1;
    private javax.swing.JLabel jLabelVehMatr;
    private javax.swing.JLabel jLabelVehMatr1;
    private javax.swing.JLabel jLabelVehMod;
    private javax.swing.JLabel jLabelVehMod1;
    private javax.swing.JLabel jLabelVehTip;
    private javax.swing.JLabel jLabelVehTip1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelVeh;
    private javax.swing.JPanel jPanelVeh1;
    private javax.swing.JSpinner jSpinnerVehFech;
    private javax.swing.JSpinner jSpinnerVehFech1;
    private javax.swing.JTextField jTextFieldCamLong;
    private javax.swing.JTextField jTextFieldCamLong1;
    private javax.swing.JTextField jTextFieldPropApe;
    private javax.swing.JTextField jTextFieldPropDNI;
    private javax.swing.JTextField jTextFieldPropNom;
    private javax.swing.JTextField jTextFieldPropTelf;
    private javax.swing.JTextField jTextFieldVehMatr;
    private javax.swing.JTextField jTextFieldVehMatr1;
    private javax.swing.JTextField jTextFieldVehMod;
    private javax.swing.JTextField jTextFieldVehMod1;
    // End of variables declaration//GEN-END:variables
}
